### ISSUE TITLE
boost filesystem v2 is deprecated [moved]

### ISSUE THREAD

**Issue by ooxi** [ooxi/violetland#61]
This is [Issue 61](http://code.google.com/p/violetland/issues/detail?id=61) moved from a Google Code project.
Added by 2012-10-25T14:09:51.000Z by [e.zagoro...@gmail.com](http://code.google.com/u/102533519110366328367/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

```
Attempt to build with boost >= 1.48 results in error:

In file included from /usr/include/boost/filesystem.hpp:15:0,
                 from /home/zag/fork/violetland/src/program.cpp:32:
/usr/include/boost/filesystem/config.hpp:16:5: error: #error Compiling Filesystem version 3 file with BOOST_FILESYSTEM_VERSION defined != 3

The possible solution is to use boost filesystem v3 API. See suggested patch in attachment.
```
